import {useEffect, useRef} from 'react'
import {useFormValue, set} from 'sanity'
import type {ObjectInputProps} from 'sanity'
import {slugify} from '../../lib/portableText'

type SlugValue = {current?: string}

// Auto-fills the slug from the title the moment there's a real title to
// slugify -- Asher's own ask (2026-08-30), after noticing Preview stays
// hidden with no explanation until the slug's own "Generate" button gets
// clicked by hand (see openInPresentation.ts's `if (!slug) return null`).
//
// Keeps following the title live, keystroke by keystroke, for as long as
// the slug field still holds exactly what THIS effect last wrote there --
// tracked via lastAutoGenerated below, not by "is it non-empty," which is
// what caused a real bug: with a plain non-empty check, typing the very
// first title character auto-fills a one-letter slug, which immediately
// reads as "already has a slug" and freezes it right there, before the
// rest of the title is even typed. Comparing against our own last write
// instead means it only stops when something ELSE changes the field --
// either a manual edit, or (via the ref resetting on remount) reopening a
// post that already has a real, previously-saved slug. That's still the
// one decision that actually matters here, confirmed directly with Asher
// before building: a slug is a permanent address once a post exists
// (search engines index it, links point to it), so only the very first
// save should ever get to invent one for free -- editing an older post's
// title later must never silently rewrite its live URL.
//
// Reuses the same slugify() src/lib/portableText.ts already has for
// heading anchor ids, rather than a second hand-rolled implementation --
// exported from there for this.
export function SlugAutoGenerateInput(props: ObjectInputProps) {
  const {value, onChange} = props
  const title = useFormValue(['title']) as string | undefined
  const currentSlug = (value as SlugValue | undefined)?.current
  const lastAutoGenerated = useRef<string | undefined>(undefined)

  useEffect(() => {
    const slugIsOurs = currentSlug === undefined || currentSlug === lastAutoGenerated.current
    if (!slugIsOurs) return

    const generated = title ? slugify(title) : ''
    if (!generated || generated === currentSlug) return

    lastAutoGenerated.current = generated
    onChange(set({_type: 'slug', current: generated}))
  }, [title, currentSlug, onChange])

  return props.renderDefault(props)
}
