// Monthly restore drill (per the ACE PRD's Phase 0 exit criteria): proves
// backups are actually restorable, not just that they exist. Never touches
// `production` -- everything happens in a throwaway dataset you create and
// delete yourself in sanity.io/manage (dataset creation/deletion needs an
// Administrator-level action that a regular Editor token can't do, so
// that part stays manual on purpose).
//
// Usage (run each step separately, in order):
//   1. In sanity.io/manage, create a new dataset, e.g. "restore-drill".
//   2. node scripts/restore-drill.mjs export   ./restore-drill-export.tar.gz
//   3. node scripts/restore-drill.mjs import   ./restore-drill-export.tar.gz  restore-drill
//   4. node scripts/restore-drill.mjs verify   restore-drill
//   5. Delete the "restore-drill" dataset in sanity.io/manage.
//
// Requires SANITY_API_WRITE_TOKEN in .env.local (Editor permission is
// enough -- dataset creation/deletion is the only part that needs more).

import { config } from "dotenv";
import { spawnSync } from "node:child_process";
import { createClient } from "@sanity/client";

config({ path: ".env.local" });

const [, , cmd, ...args] = process.argv;

function runCli(cliArgs) {
  const result = spawnSync("npx", ["sanity", ...cliArgs], {
    stdio: "inherit",
    shell: true,
    env: { ...process.env, SANITY_AUTH_TOKEN: process.env.SANITY_API_WRITE_TOKEN },
  });
  process.exit(result.status ?? 1);
}

function client(dataset) {
  return createClient({
    projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
    dataset,
    apiVersion: "2026-07-22",
    token: process.env.SANITY_API_WRITE_TOKEN,
    useCdn: false,
    perspective: "raw",
  });
}

// Fields that legitimately differ after any import and don't indicate data
// loss: revision id, update timestamp, and Sanity's internal base-revision
// tracking (all regenerated by the act of importing itself).
function stripVolatileFields(doc) {
  if (!doc) return doc;
  const { _rev, _updatedAt, _system, ...rest } = doc;
  return rest;
}

const REAL_CONTENT_TYPES = ["post", "author", "category", "contactSubmission", "sanity.imageAsset"];

if (cmd === "export") {
  const dest = args[0];
  if (!dest) { console.error("usage: node restore-drill.mjs export <destination.tar.gz>"); process.exit(1); }
  runCli(["dataset", "export", "production", dest]);
} else if (cmd === "import") {
  const [src, dataset] = args;
  if (!src || !dataset) { console.error("usage: node restore-drill.mjs import <source.tar.gz> <dataset>"); process.exit(1); }
  if (dataset === "production") { console.error("Refusing to import into production -- use a throwaway dataset."); process.exit(1); }
  runCli(["dataset", "import", src, "--dataset", dataset]);
} else if (cmd === "verify") {
  const dataset = args[0];
  if (!dataset) { console.error("usage: node restore-drill.mjs verify <dataset>"); process.exit(1); }
  const prod = client("production");
  const drill = client(dataset);
  const ids = await prod.fetch(`*[_type in $types]._id`, { types: REAL_CONTENT_TYPES });
  console.log(`Comparing ${ids.length} real content documents against production...`);
  let mismatches = 0;
  for (const id of ids) {
    const [a, b] = await Promise.all([
      prod.fetch(`*[_id == $id][0]`, { id }),
      drill.fetch(`*[_id == $id][0]`, { id }),
    ]);
    const sa = JSON.stringify(stripVolatileFields(a));
    const sb = JSON.stringify(stripVolatileFields(b));
    // Asset path/url are expected to differ -- they're scoped to the dataset name.
    const isAsset = a?._type === "sanity.imageAsset";
    if (sa !== sb && !isAsset) {
      mismatches++;
      console.log(`MISMATCH: ${id} (${a?._type ?? "?"})`);
    }
  }
  console.log(mismatches === 0
    ? `\nAll ${ids.length} documents match. Restore verified successfully.`
    : `\n${mismatches} mismatch(es) found -- if production was being actively edited during the export, this can be expected drift rather than a real problem. Investigate before trusting this drill.`);
} else {
  console.log("Usage: node scripts/restore-drill.mjs <export|import|verify> ...");
  console.log("See the comment at the top of this file for the full drill sequence.");
}
